import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { promises as fsp } from "node:fs";
import * as nodePath from "node:path";

const prod = process.argv[2] === "production";

// The legacy 1.7.2 bundle hardcodes its command IDs and settings-tab id with the old plugin
// id ("obsidian-hwp-writer:…"). Obsidian namespaces commands as "<manifest.id>:<name>", so
// shipping under a new id would make every hardcoded call miss. We rewrite the literal to the
// current manifest id at bundle time (string-only — the export/preview logic is untouched).
const PLUGIN_ID = JSON.parse(await fsp.readFile("manifest.json", "utf8")).id;
const LEGACY_OLD_ID = "obsidian-hwp-writer";

const external = [
  "obsidian",
  "electron",
  "@electron/remote",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  // kordoc 옵션/peer 의존 — 우리의 import/patch/markdownToHwpx 경로에서는 절대 실행되지 않지만
  // (OCR/ML/print/MCP 기능), kordoc의 dynamically-loaded 청크들이 이 패키지들을 문자열 require 한다.
  // external로 빼지 않으면 esbuild가 정적 스캔하다 "Could not resolve …"로 빌드가 깨진다.
  "puppeteer-core",
  "@modelcontextprotocol/sdk",
  "onnxruntime-node",
  "sharp",
  "@huggingface/transformers",
  "@hyzyla/pdfium",
  "canvas",
  // NOTE: pdfjs-dist 는 external 하지 않는다 — PDF 불러오기를 지원하므로 esbuild가 번들한다.
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`)
];

// kordoc 은 `cfb`(구버전 .hwp 바이너리 파서)를 createRequire(import.meta.url)→require2("cfb") 로
// "런타임 동적 require" 한다. esbuild 는 이를 못 따라가고, Obsidian 은 플러그인 main.js 를 eval 하며
// require/__filename 이 electron 위치라 플러그인 폴더의 node_modules 에도 닿지 못한다
// (→ "Cannot find module 'cfb'"). 따라서 cfb 는 반드시 main.js 에 "번들" 되어야 한다.
// 해법: kordoc dist 파일을 로드할 때 정적 `import * as cfb from "cfb"` 를 주입하고
// require2("cfb") 사용처를 그 바인딩으로 치환한다. 정적 import 는 esbuild 가 항상 번들한다.
// (require2 자체는 그대로 둔다 — 변수 인자 = 호출하지 않는 OCR/ML 경로용.)
const kordocBundleCfbPlugin = {
  name: "kordoc-bundle-cfb",
  setup(build) {
    // kordoc creates multiple createRequire instances (require2, require3, …);
    // cfb is loaded from TWO of them (hwp5 parser + patchHwp). Match require<digits>.
    const CFB_CALL = /\brequire\d*\(\s*["']cfb["']\s*\)/g;
    build.onLoad({ filter: /kordoc[\\/]dist[\\/].*\.(c?js|mjs)$/ }, async (args) => {
      let src = await fsp.readFile(args.path, "utf8");
      if (CFB_CALL.test(src)) {
        CFB_CALL.lastIndex = 0;
        src =
          'import * as __kordoc_cfb from "cfb";\n' +
          src.replace(CFB_CALL, "(__kordoc_cfb.default || __kordoc_cfb)");
      }
      return { contents: src, loader: "js", resolveDir: nodePath.dirname(args.path) };
    });
  }
};

// Rewrite the legacy bundle's hardcoded old plugin id → the current manifest id (command IDs,
// settings-tab id). String replacement only; the export/preview pipelines stay byte-for-byte.
const legacyRewireIdPlugin = {
  name: "legacy-rewire-id",
  setup(build) {
    build.onLoad({ filter: /legacy-main\.cjs$/ }, async (args) => {
      let src = await fsp.readFile(args.path, "utf8");
      if (PLUGIN_ID && PLUGIN_ID !== LEGACY_OLD_ID) {
        src = src.split(LEGACY_OLD_ID).join(PLUGIN_ID);
      }
      return { contents: src, loader: "js", resolveDir: nodePath.dirname(args.path) };
    });
  }
};

// Bundled deps (kordoc/jszip) inline an old `setImmediate` polyfill whose IE-only branch creates
// <script> elements. That branch never runs under Electron — `process` / `MessageChannel` are
// chosen first — but static review flags the literal as dynamic code injection. After bundling,
// swap the dead `createElement("script")` literal for an inert element. The polyfill's real
// scheduling logic is untouched, so async behavior (jszip unzip, lie promises) is unchanged.
const stripDeadScriptPlugin = {
  name: "strip-dead-ie-script",
  setup(build) {
    build.onEnd(async () => {
      try {
        let code = await fsp.readFile("main.js", "utf8");
        const n = (code.match(/createElement\("script"\)/g) || []).length;
        if (n) {
          code = code.split('createElement("script")').join('createElement("span")');
          await fsp.writeFile("main.js", code);
          console.log(`strip-dead-ie-script: neutralized ${n} dead <script> fallback(s)`);
        }
      } catch (e) {
        console.warn("strip-dead-ie-script skipped:", e.message);
      }
    });
  }
};

const options = {
  banner: {
    // kordoc 의 dist 는 module 최상단에서 createRequire(import.meta.url) 를 호출한다.
    // cjs 번들에서 import.meta 는 undefined 라 그대로 두면 로드 즉시 createRequire 가 크래시한다.
    // (require2 는 cfb 주입 이후로는 호출되지 않지만, 정의 시점의 createRequire 가 throw 하면 안 되므로 유지.)
    js:
      "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */\n" +
      "const __hwpImportMetaUrl = require('url').pathToFileURL(__filename).href;"
  },
  define: {
    "import.meta.url": "__hwpImportMetaUrl"
  },
  plugins: [kordocBundleCfbPlugin, legacyRewireIdPlugin, stripDeadScriptPlugin],
  entryPoints: ["src/main.ts"],
  bundle: true,
  external,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  platform: "node",
  minify: prod
};

if (prod) {
  await esbuild.build(options);
  console.log("Production build complete: main.js");
} else {
  const context = await esbuild.context(options);
  await context.watch();
  console.log("Watching for changes...");
}
