import { MarkdownView, Notice, Setting } from "obsidian";
import { importDocument } from "./io/kordocImport";
import { exportKordocHwpx, patchSourceExperimental } from "./io/kordocSave";
import { unpackBundledAssets } from "./io/assetUnpack";
import { readSourceContract } from "./io/frontmatter";
import { activeTableProfile } from "./io/tableStyle";
import {
  defaultDocumentStyleProfile,
  legacyTemplatePageLayout,
  legacyTemplateStyleCache,
  type DocumentStyleProfile
} from "./io/documentStyle";
import {
  activeDocumentStyle,
  activeDocumentTemplate,
  activeTemplateId,
  availableDocumentTemplates,
  importDocumentStyle,
  migrateDocumentStyleSettingsInMemory,
  saveDocumentStyle,
  setActiveDocumentTemplate
} from "./io/documentStyleSettings";
import { HanmarkExportModal } from "./ui/HanmarkExportModal";
import { HwpxTemplateManagerModal } from "./ui/HwpxTemplateManagerModal";
import { QuickHwpxPreviewView, QUICK_HWPX_PREVIEW_VIEW } from "./ui/QuickHwpxPreviewView";
import { DocumentStyleModal } from "./ui/DocumentStyleModal";

// 2.4 keeps the old bundle only as a compatibility shell for the toolbar, HTML and DOCX.
// The HWPX route never initializes its Python/pypandoc-hwpx bridge.
const legacyModule: any = require("../legacy-main.cjs");
const LegacyPlugin: any = legacyModule?.default ?? legacyModule;

type ExportTab = "hwpx" | "other";

const RETIRED_SETTINGS_KEYS = [
  "pythonPath",
  "defaultTemplatePath",
  "cachedTemplateStyles",
  "cachedTemplatePageLayout",
  "hanmarkDocumentStyle",
  "hanmarkDocumentStylePreset",
  "hanmarkTableProfile",
  "hanmarkTableProfileName"
] as const;

function removeRetiredSettings(settings: any): boolean {
  if (!settings || typeof settings !== "object") return false;
  let changed = false;
  for (const key of RETIRED_SETTINGS_KEYS) {
    if (!Object.prototype.hasOwnProperty.call(settings, key)) continue;
    delete settings[key];
    changed = true;
  }
  return changed;
}

function directChildHeadings(container: HTMLElement): HTMLHeadingElement[] {
  return Array.from(container.children).filter((element): element is HTMLHeadingElement => element.tagName === "H2");
}

function removeHeadingSection(container: HTMLElement, matches: (text: string) => boolean): void {
  const heading = directChildHeadings(container).find((item) => matches(item.textContent || ""));
  if (!heading) return;
  let node: ChildNode | null = heading;
  while (node) {
    const next = node.nextSibling;
    if (node !== heading && node instanceof HTMLElement && node.tagName === "H2") break;
    node.remove();
    node = next;
  }
}

export default class HanmarkPlugin extends LegacyPlugin {
  private _canonicalSettings: any = null;
  private _hanmarkSettingsPatched = false;

  async onload(): Promise<void> {
    // DOCX still uses the bundled Word assets. HWPX itself is generated by Kordoc.
    await unpackBundledAssets(this);
    await super.onload();

    // Defense in depth: even an unanticipated legacy caller cannot enter the retired
    // pypandoc-hwpx method. All HWPX creation is routed through the Kordoc export center.
    if ((this as any).exportManager) {
      (this as any).exportManager.exportHwpx = () => this.openExportCenter("hwpx");
    }

    this.registerView(
      QUICK_HWPX_PREVIEW_VIEW,
      (leaf: any) => new QuickHwpxPreviewView(leaf, () => activeTableProfile(this), () => activeDocumentStyle(this))
    );

    this.addCommand({
      id: "import-hwp-document",
      name: "한글·문서 불러오기 (HWP/HWPX/PDF/DOCX/XLSX → Markdown)",
      callback: () => importDocument(this.app, this)
    });
    this.addCommand({
      id: "open-export-center",
      name: "HanMark 내보내기",
      callback: () => this.openExportCenter("hwpx")
    });
    this.addCommand({
      id: "save-hwp-roundtrip",
      name: "한글로 저장 · HanMark 내보내기",
      callback: () => this.openExportCenter("hwpx")
    });
    this.addCommand({
      id: "quick-export-hwpx",
      name: "빠른 HWPX 내보내기 (설치 불필요)",
      callback: () => exportKordocHwpx(this.app, this, { mode: "quick-hwpx" })
    });
    this.addCommand({
      id: "gongmun-export-hwpx",
      name: "공문서 HWPX 내보내기…",
      callback: () => this.openExportCenter("hwpx")
    });
    this.addCommand({
      id: "patch-hwp-experimental",
      name: "원본 형식 보존 저장 (.hwp/.hwpx 수정본)",
      callback: () => patchSourceExperimental(this.app, this)
    });
    this.addCommand({
      id: "quick-hwpx-preview",
      name: "빠른 HWPX 미리보기 열기/닫기",
      callback: () => this.activateQuickPreview()
    });
    this.addCommand({
      id: "manage-hwpx-templates",
      name: "HWPX 템플릿 관리",
      callback: () => this.openTemplateManager()
    });
    this.addCommand({
      id: "import-document-style",
      name: "HWPX를 사용자 템플릿으로 가져오기",
      callback: () => this.importDocumentStyleAndRefresh()
    });
    this.addCommand({
      id: "edit-document-style",
      name: "현재 HWPX 템플릿 편집",
      callback: () => this.openDocumentStyleEditor()
    });

    this.rewireLegacyCommandAliases();
    this.patchToolbarForGateway();
  }

  /** The legacy layout-ready hook lands here. It must remain external-process free. */
  async initializePlugin(): Promise<void> {
    console.log("HanMark: Kordoc 4.2.5 bundled HWPX engine ready (no Python/pypandoc-hwpx)");
  }

  /** The inherited font reload button also lands here; keep it local and process-free. */
  async refreshTemplateStyles(): Promise<void> {
    (this as any).fontCatalog?.invalidate?.();
    this.refreshQuickPreviews();
    (this as any).refreshAllDocxPreviews?.();
  }

  async loadSettings(): Promise<void> {
    await super.loadSettings();
    const fresh = (this as any).settings;
    if (fresh) {
      fresh.isFirstRun = false;
    }
    if (this._canonicalSettings && this._canonicalSettings !== fresh) {
      Object.assign(this._canonicalSettings, fresh);
      (this as any).settings = this._canonicalSettings;
    } else {
      this._canonicalSettings = fresh;
    }
    const changed = migrateDocumentStyleSettingsInMemory(this) || removeRetiredSettings((this as any).settings);
    if (changed) await this.saveSettings();
  }

  async saveSettings(): Promise<void> {
    if (!this._canonicalSettings) this._canonicalSettings = (this as any).settings;
    if ((this as any).settings) {
      (this as any).settings.isFirstRun = false;
      removeRetiredSettings((this as any).settings);
    }
    await super.saveSettings();
    const after = (this as any).settings;
    removeRetiredSettings(after);
    const canonical = this._canonicalSettings;
    if (canonical && after && after !== canonical) {
      Object.assign(canonical, after);
      removeRetiredSettings(canonical);
      (this as any).settings = canonical;
    }
    // The inherited normalizer still carries old defaults. Persist once more after pruning
    // so data.json no longer advertises Python or the removed one-slot HWPX template path.
    await this.saveData((this as any).settings);
  }

  addSettingTab(tab: any): any {
    const result = super.addSettingTab(tab);
    if (this._hanmarkSettingsPatched || tab?.plugin !== this || typeof tab.display !== "function") return result;
    const originalDisplay = tab.display.bind(tab);
    tab.display = () => {
      originalDisplay();
      this.decorateSettings(tab.containerEl);
    };
    this._hanmarkSettingsPatched = true;
    return result;
  }

  private decorateSettings(container: HTMLElement): void {
    // Remove the retired three-step installer and the old one-slot HWPX picker.
    removeHeadingSection(container, (text) => text.includes("Python / Pandoc"));
    removeHeadingSection(container, (text) => text.includes("HWPX 템플릿"));

    const heading = container.querySelector("h1");
    heading?.setText("HanMark 설정");
    if (!heading || container.querySelector(".hanmark-settings-engine")) return;

    const status = createDiv({ cls: "hanmark-engine-status hanmark-settings-engine" });
    status.createEl("strong", { text: "HWPX 기본 엔진 · Kordoc 4.2.5 내장" });
    status.createEl("span", {
      text: "Python·pypandoc-hwpx 없이 HWPX를 만들며, 원격·Vault 이미지를 문서 안에 포함합니다."
    });
    heading.insertAdjacentElement("afterend", status);

    const templateSection = createDiv({ cls: "hanmark-settings-template-library" });
    templateSection.createEl("h2", { text: "HWPX 템플릿" });
    const active = activeDocumentTemplate(this);
    new Setting(templateSection)
      .setName(active.name)
      .setDesc(
        `${active.builtIn ? "내장" : "사용자"} 템플릿 · 문서 스타일 ${active.documentStyle ? "포함" : "Kordoc 기본"}` +
        ` · 표 스타일 ${active.tableStyle?.tables?.length ? `${active.tableStyle.tables.length}개 포함` : "없음"}`
      )
      .addDropdown((dropdown) => {
        for (const item of availableDocumentTemplates(this)) dropdown.addOption(item.id, item.name);
        dropdown.setValue(active.id);
        dropdown.onChange(async (id) => {
          try {
            await setActiveDocumentTemplate(this, id);
            this.refreshQuickPreviews();
            (this.app as any).setting?.activeTab?.display?.();
          } catch (error: any) {
            new Notice(error?.message || String(error));
          }
        });
      })
      .addButton((button) => button.setButtonText("관리").setCta().onClick(() => this.openTemplateManager()))
      .addButton((button) => button.setButtonText("현재 템플릿 편집").onClick(() => this.openDocumentStyleEditor()))
      .addButton((button) => button.setButtonText("HWPX에서 추가").onClick(async () => {
        try {
          if (await this.importDocumentStyleAndRefresh()) (this.app as any).setting?.activeTab?.display?.();
        } catch (error: any) {
          new Notice(error?.message || String(error));
        }
      }));
    status.insertAdjacentElement("afterend", templateSection);

    const docxDetails = createEl("details", { cls: "hanmark-docx-settings" });
    docxDetails.createEl("summary", { text: "DOCX용 Pandoc 설정 (선택)" });
    docxDetails.createEl("p", {
      cls: "setting-item-description",
      text: "DOCX 내보내기에만 사용합니다. HWPX와 HTML에는 Pandoc도 Python도 필요하지 않습니다."
    });
    new Setting(docxDetails)
      .setName("Pandoc 경로")
      .setDesc("예: pandoc 또는 C:\\Program Files\\Pandoc\\pandoc.exe")
      .addText((text) => text
        .setPlaceholder("pandoc")
        .setValue(String((this as any).settings?.pandocPath || "pandoc"))
        .onChange(async (value) => {
          (this as any).settings.pandocPath = value.trim() || "pandoc";
          await this.saveSettings();
        }));
    templateSection.insertAdjacentElement("afterend", docxDetails);
  }

  private openExportCenter(initialTab: ExportTab = "hwpx"): void {
    new HanmarkExportModal(this.app, {
      sourcePatchAvailable: () => {
        const file = this.app.workspace.getActiveFile();
        const contract = file ? readSourceContract(this.app, file) : null;
        return contract?.["hwp-source-format"] === "hwp" || contract?.["hwp-source-format"] === "hwpx";
      },
      activeTemplateId: () => activeTemplateId(this),
      templateChoices: () => availableDocumentTemplates(this).map(({ id, name }) => ({ id, name })),
      activeTemplateSummary: () => {
        const item = activeDocumentTemplate(this);
        const table = item.tableStyle?.tables?.length ? `표 스타일 ${item.tableStyle.tables.length}개` : "표 스타일 없음";
        return `${item.builtIn ? "내장" : "사용자"} · ${item.documentStyle ? "문서 스타일 포함" : "Kordoc 기본"} · ${table}`;
      },
      selectTemplate: async (id) => {
        await setActiveDocumentTemplate(this, id);
        this.refreshQuickPreviews();
      },
      openTemplateManager: () => this.openTemplateManager(),
      exportKordoc: (mode, preset) => exportKordocHwpx(this.app, this, { mode, gongmunPreset: preset }),
      patchSource: () => patchSourceExperimental(this.app, this),
      runOther: (mode) => this.runOtherExport(mode),
      openPreview: () => this.activateQuickPreview()
    }, initialTab).open();
  }

  private async runOtherExport(mode: "docx" | "html"): Promise<void> {
    const view = this.app.workspace.getActiveViewOfType(MarkdownView);
    if (!view?.file) {
      new Notice("내보낼 마크다운 노트를 여세요.");
      return;
    }
    const manager: any = (this as any).exportManager;
    if (!manager) throw new Error("내보내기 엔진을 초기화하지 못했습니다.");

    if (mode === "docx") {
      await manager.exportDocx(view.editor, view);
      return;
    }

    // The compatibility HTML writer reads the old cache fields. Feed it the active Kordoc
    // template only for the duration of this export; never persist those retired settings.
    const settings = (this as any).settings;
    const oldStyles = settings.cachedTemplateStyles;
    const oldPage = settings.cachedTemplatePageLayout;
    const profile = activeDocumentStyle(this);
    try {
      if (profile) {
        settings.cachedTemplateStyles = legacyTemplateStyleCache(profile);
        settings.cachedTemplatePageLayout = legacyTemplatePageLayout(profile);
      } else {
        delete settings.cachedTemplateStyles;
        delete settings.cachedTemplatePageLayout;
      }
      await manager.exportHtml(view.editor, view);
    } finally {
      if (oldStyles === undefined) delete settings.cachedTemplateStyles;
      else settings.cachedTemplateStyles = oldStyles;
      if (oldPage === undefined) delete settings.cachedTemplatePageLayout;
      else settings.cachedTemplatePageLayout = oldPage;
    }
  }

  private async activateQuickPreview(): Promise<void> {
    const existing = this.app.workspace.getLeavesOfType(QUICK_HWPX_PREVIEW_VIEW);
    if (existing.length) {
      existing.forEach((leaf: any) => leaf.detach());
      return;
    }
    const leaf = this.app.workspace.getLeaf("split", "vertical");
    await leaf.setViewState({ type: QUICK_HWPX_PREVIEW_VIEW, active: true });
    this.app.workspace.revealLeaf(leaf);
  }

  private refreshQuickPreviews(): void {
    this.app.workspace.getLeavesOfType(QUICK_HWPX_PREVIEW_VIEW).forEach((leaf: any) => {
      (leaf.view as QuickHwpxPreviewView)?.forceRefresh?.();
    });
  }

  private async importDocumentStyleAndRefresh(): Promise<boolean> {
    const changed = await importDocumentStyle(this);
    if (changed) this.refreshQuickPreviews();
    return changed;
  }

  private openDocumentStyleEditor(profile: DocumentStyleProfile = activeDocumentStyle(this) || defaultDocumentStyleProfile()): void {
    new DocumentStyleModal(this.app, profile, async (savedProfile) => {
      await saveDocumentStyle(this, savedProfile);
      this.refreshQuickPreviews();
      (this.app as any).setting?.activeTab?.display?.();
    }).open();
  }

  private openTemplateManager(): void {
    new HwpxTemplateManagerModal(
      this.app,
      this,
      (profile) => this.openDocumentStyleEditor(profile),
      () => {
        this.refreshQuickPreviews();
        (this.app as any).setting?.activeTab?.display?.();
      }
    ).open();
  }

  private openPluginSettings(): void {
    const setting = (this.app as any).setting;
    setting?.open?.();
    setting?.openTabById?.(this.manifest.id);
    new Notice("DOCX에만 Pandoc 설정이 필요합니다.");
  }

  /** Preserve public command IDs while retiring the old pypandoc-hwpx actions. */
  private rewireLegacyCommandAliases(): void {
    const registry = (this.app as any).commands?.commands;
    if (!registry) return;
    const command = (id: string): any => registry[`${this.manifest.id}:${id}`];
    const rewire = (id: string, name: string, callback: () => void): void => {
      const item = command(id);
      if (!item) return;
      item.callback = callback;
      item.editorCallback = callback;
      item.name = name;
    };
    rewire("export-hwpx", "HanMark HWPX 내보내기", () => this.openExportCenter("hwpx"));
    rewire("export-docx", "HanMark DOCX 내보내기", () => this.openExportCenter("other"));
    rewire("export-html", "HanMark HTML 내보내기", () => this.openExportCenter("other"));
    rewire("select-template", "HWPX 템플릿 관리", () => this.openTemplateManager());
    rewire("select-hwpx-template", "HWPX 템플릿 관리", () => this.openTemplateManager());
    rewire("show-setup-guide", "DOCX용 Pandoc 설정", () => this.openPluginSettings());
    rewire("toggle-preview", "빠른 HWPX 미리보기 열기/닫기", () => void this.activateQuickPreview());
    rewire("toggle-hwp-preview", "빠른 HWPX 미리보기 열기/닫기", () => void this.activateQuickPreview());
  }

  private patchToolbarForGateway(): void {
    const rewire = (root: ParentNode): void => {
      root.querySelectorAll("button").forEach((button) => {
        if ((button as any).__hanmarkGatewayWired) return;
        const label = `${button.getAttribute("aria-label") || ""} ${button.textContent || ""}`.trim();

        if (label.includes("설치 가이드")) {
          button.remove();
          return;
        }

        let action: (() => void) | null = null;
        let ariaLabel: string | null = null;
        let visibleText: string | null = null;
        if (label.includes("불러오기")) action = () => void importDocument(this.app, this);
        else if (label.includes("HWPX") && label.includes("내보내기")) {
          action = () => this.openExportCenter("hwpx");
          ariaLabel = "HWPX 내보내기";
        } else if ((label.includes("DOCX") || label.includes("HTML")) && label.includes("내보내기")) {
          action = () => this.openExportCenter("other");
        } else if (label.includes("분할") && !label.toLowerCase().includes("docx")) {
          action = () => void this.activateQuickPreview();
          ariaLabel = "빠른 HWPX 미리보기";
        } else if (label.includes("템플릿") && !label.includes("워드")) {
          action = () => this.openTemplateManager();
          ariaLabel = "HWPX 템플릿 관리";
          visibleText = "HWPX 템플릿";
        }
        if (!action) return;

        const replacement = button.cloneNode(true) as HTMLButtonElement;
        (replacement as any).__hanmarkGatewayWired = true;
        if (ariaLabel) {
          replacement.setAttribute("aria-label", ariaLabel);
          replacement.setAttribute("title", ariaLabel);
        }
        if (visibleText) replacement.setText(visibleText);
        replacement.addEventListener("mousedown", (event) => {
          event.preventDefault();
          event.stopPropagation();
        });
        replacement.addEventListener("click", (event) => {
          event.preventDefault();
          event.stopPropagation();
          action?.();
        });
        button.replaceWith(replacement);
      });
    };

    const manager: any = (this as any).toolbarManager;
    if (manager?.renderMainToolbar) {
      const original = manager.renderMainToolbar.bind(manager);
      manager.renderMainToolbar = (element: HTMLElement) => {
        original(element);
        rewire(element);
      };
      try {
        manager.removeToolbar?.();
        const activeLeaf = this.app.workspace.getActiveViewOfType(MarkdownView)?.leaf;
        if (activeLeaf && manager.visible) manager.injectToolbar?.(activeLeaf);
      } catch (error) {
        console.warn("[hanmark] toolbar re-inject failed:", error);
      }
    }
    document.querySelectorAll(".hwp-toolbar-main").forEach((element) => rewire(element));
  }

  async onunload(): Promise<void> {
    await super.onunload();
  }
}
